/**
 * @author Kevin
 * @description: 问答
 * path config
 * @Date: 2024/11/12
 */

export const FAQS_LIST = [
	{
		title_en: "What is Sprunki Incredibox?",
		content_en:
			"Sprunki Incredibox, available at sprunki.io, is a fan-made mod of the original Incredibox game that enhances the music creation experience with unique characters and soundscapes.",
		title_zh: "什么是 Sprunki Incredibox？",
		content_zh: "Sprunki Incredibox 可在 sprunki.io 上找到，它是原版 Incredibox 游戏的粉丝制作的模组，可通过独特的角色和音景增强音乐创作体验。",
		title_ja: "Sprunki Incrediboxとは何ですか？",
		content_ja: "sprunki.ioで利用できるSprunki Incrediboxは、オリジナルのIncrediboxゲームのファンが作成したModで、ユニークなキャラクターとサウンドスケープで音楽作成体験を強化します。",
		title_fr: "Qu'est-ce que Sprunki Incredibox?",
		content_fr: "Sprunki Incredibox, disponible sur sprunki.io, est un mod réalisé par des fans du jeu original Incredibox qui améliore l'expérience de création musicale avec des personnages et des paysages sonores uniques.",
		title_es: "¿Qué es Sprunki Incredibox?",
		content_es: "Sprunki Incredibox, disponible en sprunki.io, es un mod hecho por fans del juego original Incredibox que mejora la experiencia de creación musical con personajes y paisajes sonoros únicos.",
		title_pt: "O que é o Sprunki Incredibox?",
		content_pt: "Sprunki Incredibox, disponível em sprunki.io, é um mod feito por fãs do jogo original Incredibox que melhora a experiência de criação musical com personagens e paisagens sonoras únicas.",
		title_ms: "Apakah Sprunki Incredibox?",
		content_ms: "Sprunki Incredibox, tersedia di sprunki.io, adalah mod buatan peminat dari permainan Incredibox yang asal yang meningkatkan pengalaman penciptaan muzik dengan watak dan landskap bunyi yang unik。",
	},
	{
		title_en: "How does Sprunki Incredibox differ from the original Incredibox?",
		content_en:
			"It introduces new characters, sounds, and vibrant visuals, offering a fresh twist on the original game's concept.",
		title_zh: "Sprunki Incredibox 与原始 Incredibox 有何不同？",
		content_zh: "它引入了新的角色、声音和生动的视觉效果，为原始游戏的概念提供了新鲜的诠释。",
		title_ja: "Sprunki IncrediboxはオリジナルのIncrediboxとどう違うのですか？",
		content_ja: "新しいキャラクター、音、そして鮮やかなビジュアルを導入し、オリジナルのゲームコンセプトに新しいひねりを加えています。",
		title_fr: "Comment Sprunki Incredibox diffère-t-il de l'Incredibox original?",
		content_fr: "Il introduit de nouveaux personnages, sons et visuels vibrants, offrant une nouvelle interprétation du concept du jeu original.",
		title_es: "¿En qué se diferencia Sprunki Incredibox del Incredibox original?",
		content_es: "Introduce nuevos personajes, sonidos y visuales vibrantes, ofreciendo un giro fresco al concepto del juego original.",
		title_pt: "Como o Sprunki Incredibox difere do Incredibox original?",
		content_pt: "Ele introduz novos personagens, sons e visuais vibrantes, oferecendo uma nova interpretação do conceito do jogo original.",
		title_ms: "Bagaimana Sprunki Incredibox berbeza daripada Incredibox yang asal?",
		content_ms: "Ia memperkenalkan watak, bunyi dan visual yang bersemangat baharu, menawarkan kelainan segar pada konsep permainan asal.",
	},
	{
		title_en: "Why should I play Sprunki Incredibox?",
		content_en: "Sprunki Incredibox offers a creative and fun way to make music, with a variety of modes and quirky elements that make each session unique.",
		title_zh: "我为什么要玩 Sprunki Incredibox？",
		content_zh: "Sprunki Incredibox 提供一种富有创意且有趣的音乐制作方式，其多种模式和奇特元素使每次演奏都独一无二。",
		title_ja: "なぜSprunki Incrediboxをプレイすべきですか？",
		content_ja: "Sprunki Incrediboxは、創造的で楽しい音楽の作成方法を提供し、さまざまなモードと風変わりな要素が各セッションをユニークにします。",
		title_fr: "Pourquoi devrais-je jouer à Sprunki Incredibox?",
		content_fr: "Sprunki Incredibox offre une façon créative et amusante de créer de la musique, avec une variété de modes et d'éléments excentriques qui rendent chaque session unique.",
		title_es: "¿Por qué debería jugar Sprunki Incredibox?",
		content_es: "Sprunki Incredibox ofrece una forma creativa y divertida de hacer música, con una variedad de modos y elementos peculiares que hacen que cada sesión sea única.",
		title_pt: "Por que devo jogar Sprunki Incredibox?",
		content_pt: "Sprunki Incredibox oferece uma maneira criativa e divertida de fazer música, com uma variedade de modos e elementos peculiares que tornam cada sessão única.",
		title_ms: "Mengapa saya perlu bermain Sprunki Incredibox?",
		content_ms: "Sprunki Incredibox menawarkan cara yang kreatif dan menyeronokkan untuk membuat muzik, dengan pelbagai mod dan elemen pelik yang menjadikan setiap sesi unik.",
	},
	{
		title_en: "Is Sprunki Incredibox free to use?",
		content_en: "Yes, it is completely free to play and can be accessed online at sprunkimod.app.",
		title_zh: "Sprunki Incredibox 可以免费使用吗？",
		content_zh: "是的，它完全免费，可以在 sprunkimod.app 上在线访问。",
		title_ja: "Sprunki Incrediboxは無料で使用できますか？",
		content_ja: "はい、完全に無料でプレイでき、sprunkimod.appでオンラインでアクセスできます。",
		title_fr: "Sprunki Incredibox est-il gratuit?",
		content_fr: "Oui, il est complètement gratuit et accessible en ligne sur sprunkimod.app.",
		title_es: "¿Sprunki Incredibox es gratis?",
		content_es: "Sí, es completamente gratis y se puede acceder en línea en sprunkimod.app.",
		title_pt: "Sprunki Incredibox é gratuito?",
		content_pt: "Sim, é completamente gratuito e pode ser acessado online em sprunkimod.app.",
		title_ms: "Adakah Sprunki Incredibox percuma untuk digunakan?",
		content_ms: "Ya, ia adalah percuma untuk dimainkan dan boleh diakses dalam talian di sprunkimod.app.",
	},
	{
		title_en: "How do I create music in Sprunki Incredibox?",
		content_en: "Simply drag and drop characters to mix sounds and add effects, creating your own unique compositions.",
		title_zh: "如何在 Sprunki Incredibox 中创作音乐？",
		content_zh: "只需拖放字符即可混合声音并添加效果，从而创建自己独特的作品。",
		title_ja: "Sprunki Incrediboxでどのように音楽を作成しますか？",
		content_ja: "キャラクターをドラッグアンドドロップするだけで、サウンドをミックスし、エフェクトを追加して、独自の作曲を作成できます。",
		title_fr: "Comment créer de la musique dans Sprunki Incredibox?",
		content_fr: "Il suffit de glisser-déposer des personnages pour mixer les sons et ajouter des effets, créant ainsi vos propres compositions uniques.",
		title_es: "¿Cómo creo música en Sprunki Incredibox?",
		content_es: "Simplemente arrastre y suelte personajes para mezclar sonidos y agregar efectos, creando sus propias composiciones únicas.",
		title_pt: "Como criar música no Sprunki Incredibox?",
		content_pt: "Basta arrastar e soltar personagens para misturar sons e adicionar efeitos, criando suas próprias composições únicas.",
		title_ms: "Bagaimana saya membuat muzik dalam Sprunki Incredibox?",
		content_ms: "Hanya seret dan lepas watak untuk mencampur bunyi dan menambah kesan, mencipta gubahan unik anda sendiri.",
	},
	{
		title_en: "Can I save and share my music creations?",
		content_en: "Yes, you can save your creations and share them with friends or the Sprunki community.",
		title_zh: "我可以保存并分享我的音乐创作吗？",
		content_zh: "是的，您可以保存您的创作并与朋友或 Sprunki 社区分享。",
		title_ja: "自分の音楽作品を保存して共有できますか？",
		content_ja: "はい、作成した作品を保存して、友人やSprunkiコミュニティと共有できます。",
		title_fr: "Puis-je sauvegarder et partager mes créations musicales?",
		content_fr: "Oui, vous pouvez sauvegarder vos créations et les partager avec des amis ou la communauté Sprunki.",
		title_es: "¿Puedo guardar y compartir mis creaciones musicales?",
		content_es: "Sí, puede guardar sus creaciones y compartirlas con amigos o la comunidad de Sprunki.",
		title_pt: "Posso salvar e compartilhar minhas criações musicais?",
		content_pt: "Sim, você pode salvar suas criações e compartilhá-las com amigos ou com a comunidade Sprunki.",
		title_ms: "Bolehkah saya menyimpan dan berkongsi ciptaan muzik saya?",
		content_ms: "Ya, anda boleh menyimpan ciptaan anda dan berkongsi dengan rakan atau komuniti Sprunki.",
	},
	{
		title_en: "What are the different modes available in Sprunki Incredibox?",
		content_en: "Modes like Classic, Disco Fever, Space Odyssey, and Time Warp offer unique themes and sounds.",
		title_zh: "Sprunki Incredibox 有哪些不同的模式？",
		content_zh: "经典、迪斯科狂热、太空漫游和时间扭曲等模式提供独特的主题和声音。",
		title_ja: "Sprunki Incrediboxで利用できるさまざまなモードは何ですか？",
		content_ja: "クラシック、ディスコフィーバー、スペースオデッセイ、タイムワープなどのモードは、ユニークなテーマとサウンドを提供します。",
		title_fr: "Quels sont les différents modes disponibles dans Sprunki Incredibox?",
		content_fr: "Les modes tels que Classique, Disco Fever, Space Odyssey et Time Warp offrent des thèmes et des sons uniques.",
		title_es: "¿Cuáles son los diferentes modos disponibles en Sprunki Incredibox?",
		content_es: "Modos como Classic, Disco Fever, Space Odyssey y Time Warp ofrecen temas y sonidos únicos.",
		title_pt: "Quais são os diferentes modos disponíveis no Sprunki Incredibox?",
		content_pt: "Modos como Classic, Disco Fever, Space Odyssey e Time Warp oferecem temas e sons únicos.",
		title_ms: "Apakah mod yang berbeza tersedia dalam Sprunki Incredibox?",
		content_ms: "Mod seperti Classic, Disco Fever, Space Odyssey, dan Time Warp menawarkan tema dan bunyi yang unik.",
	},
];
